version: "3"

volumes:
  db_data:

services:

  api:
    image: djangochat/api
    ports:
      - 8000:8000
    env_file:
      - app.default.env
    volumes: 
      - ./api:/api
    depends_on:
      - postgres

  # frontend:
  #   image: djangochat/frontend
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - app.default.env
  #   volumes: 
  #     - ./frontend:/frontend

  postgres:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - app.default.env
