version: "3"

volumes:
  pg_data:

services:

  api:
    image: djangochat/api
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    env_file:
      - app.default.env
    volumes: 
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379

  # frontend:
  #   image: djangochat/frontend
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - app.default.env
  #   volumes: 
  #     - ./frontend:/frontend

  postgres:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - app.default.env
